moved perl and mysql to plugins, fixed cifs failure

diff --git a/branches/0.4alpha/core/platform/pulsarroot/bin/plugin b/branches/0.4alpha/core/platform/pulsarroot/bin/plugin
--- a/branches/0.4alpha/core/platform/pulsarroot/bin/plugin
+++ b/branches/0.4alpha/core/platform/pulsarroot/bin/plugin
@@ -7,8 +7,8 @@
 # Variables
 WORKDIR=/pulsarroot
 APPDIR=/pulsarroot/plugins
-MIRROR="http://download.berlios.de/pulsaros"
-SYNTAX="plugin list | install | activate | deactivate | deinstall 'pluginname'"
+MIRROR="http://10.0.0.144/~tbrandstetter/pulsaros"
+SYNTAX="plugin list | install | deinstall 'pluginname'"
 alias WGET='wget --directory-prefix=$WORKDIR -nc -q'
 
 # Functions
@@ -25,24 +25,56 @@ get_plugin()
 		printf "\nError retrieving Plugin list - please try it again!\n\n"
 		[ -f HTTP_NOT_FOUND.html.var ] && rm HTTP_NOT_FOUND.html.var && exit 1
 	fi
-	if [[ $# = 1 && `cat plugin.list|grep -wc ${1}` -ne 1 ]]; then
+	if [[ $# = 1 && `cat plugin.list|grep -wc ${1}` -lt 1 ]]; then
 		printf "\nPlugin name not found!\n\n"
 		rm plugin.list
-		exit 1
+		exit 1		
 	fi
+}
+
+check_plugin()
+{
+	get_plugin $1
+	case $2 in
+		install)
+			[ -d $APPDIR/${1} ] && printf "\nPlugin already installed!\n" && exit 1
+			debs=`grep "^${1}" plugin.list|awk -F'|' '{print $3}'`
+			for i in `echo $debs |awk -F',' '{ for (i = NF; i > 0; --i) print $i }'`; do
+				if [ ! -d $APPDIR/${i} ]; then
+					printf "\nDependency check failed - plugin ${i} must be installed first!\n"
+					dependency=1
+				fi
+			done 
+			[ "$dependency" -eq 1 ] && exit 1
+		;;
+		deinstall)
+			[ ! -d $APPDIR/${1} ] && printf "\nPlugin not installed!\n" && exit 1
+			debs=`grep -v "^${1}" plugin.list|grep "${1}" | awk -F'|' '{print $1}'`
+			for i in `echo $debs`; do
+				if [ -d $APPDIR/${i} ]; then
+					printf "\nDependency check failed - ${i} must be deinstalled first!\n"
+					dependency=1
+				fi
+			done 
+			[ "$dependency" -eq 1 ] && exit 1
+		;;
+		*)
+			printf "API error - contact developer!"
+		;;
+	esac
 }
 
 list_plugins()
 {
 	# get plugin.list file
-	get_plugin
+	WGET ${MIRROR}/plugin.list
 	# create plugin list
 	printf "\n\n"
-	printf "Plugin Name\t\tActual version\t\tInstalled Version\tStatus\n"
+	printf "Plugin Name          Actual version\t\tInstalled Version\tStatus\n"
 	printf "=================================================================================\n"
 	for i in `cat plugin.list`; do
-		plugin_name=`echo $i | awk -F- '{print $1}'`
-		plugin_version=`echo $i | awk -F- '{print $2}'`
+		plugin_name=`echo $i | awk  -F'|' '{print $1}'`
+		plugin_version=`echo $i | awk -F'|' '{print $2}'`
 		if [ ! -d $APPDIR/${plugin_name} ]; then
 			plugin_installed="-"
 			plugin_status="-"
@@ -50,7 +82,7 @@ list_plugins()
 			plugin_installed=`cat $APPDIR/${plugin_name}/.plugin_version`
 			plugin_status=`cat $APPDIR/${plugin_name}/.plugin_status`
 		fi
-		printf "${plugin_name}\t\t${plugin_version}\t\t\t${plugin_installed}\t\t\t${plugin_status}"
+		printf "${plugin_name}          ${plugin_version}\t\t\t${plugin_installed}\t\t\t${plugin_status}\n"
 	done
 	printf "\n\n"
 	# cleanup
@@ -59,7 +91,7 @@ list_plugins()
 
 install_plugin()
 {
-	get_plugin $1
+	check_plugin $1 "install"
 	# check if plugin is already installed
 	if [ -d $APPDIR/plugins/${1} ]; then
 		printf "Plugin is already installed. Check for updates with the 'update' parameter.\n\n"
@@ -79,7 +111,9 @@ install_plugin()
 				exit 1
 			else 
 				echo "installed" > ${APPDIR}/${1}/.plugin_status
-				printf "\nPlugin successfully installed!\n\n"
+				[ "`grep "^${1}" plugin.list|awk -F'|' '{print $4}'`" == "A" ] &&  activate_plugin ${1}
+				printf "\nPlugin successfully installed and activated!\n\n"
+				
 			fi
 		else
 			printf "Error downloading the plugin - please try it again!\n\n"
@@ -95,26 +129,23 @@ update_plugin()
 
 activate_plugin()
 {
-	get_plugin $1	
 	printf "Activating plugin ${1} ..."
 	svcadm enable ${1}
-	sleep 4
+	sleep 5
 	if [ `svcs ${1}|tail -1|awk '{print $1}'` != "online" ]; then
 		printf "Warning: Plugin activation failed - please take a look in /var/svc/log/application-${1}:default.log, correct the error and try it again!\n\n"
 		exit 1
 	else
-		printf "activated" > ${APPDIR}/${1}/.plugin_status
 		printf "\nPlugin successfully activated!\n\n"
 	fi
 }
 
 deactivate_plugin()
 {
-	get_plugin $1
 	printf "Deactivating plugin ${1} ..."
 	svcadm disable ${1}
+	sleep 5
 	if [ $? -eq 0 ]; then
-		printf "deactivated" > ${APPDIR}/${1}/.plugin_status
 		printf "\nPlugin successfully deactivated!\n\n"
 	else
 		printf "Warning: Plugin deactivation failed - please take a look in /var/svc/log/application-${1}:default.log, correct the error and try it again!\n\n"
@@ -124,14 +155,15 @@ deactivate_plugin()
 
 deinstall_plugin()
 {
-	get_plugin $1
+	check_plugin $1 "deinstall"
+	[ "`grep "^${1}" plugin.list|awk -F'|' '{print $4}'`" == "A" ] && deactivate_plugin ${1}
 	printf "Deinstalling plugin..."
 	${APPDIR}/${1}/scripts/main.sh deinstall
 	if [ $? != 0 ]; then
 		printf "Warning plugin deinstallation failed - please try it again!\n\n"
 		exit 1
 	else 
-		printf "\nPlugin successfully deinstalled!\n\n"
+		printf "\nPlugin successfully deactivated and deinstalled!\n\n"
 	fi
 }
 
@@ -154,12 +186,6 @@ case $1 in
 	;;
 	update)
 		update_plugin $2
-	;;
-	activate)
-		activate_plugin $2
-	;;
-	deactivate)
-		deactivate_plugin $2
 	;;
 	deinstall)
 		deinstall_plugin $2
